# Generated by Django 2.2.1 on 2019-07-22 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='kml_drone_path/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('name', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fCorner', models.CharField(max_length=400)),
                ('sCorner', models.CharField(max_length=400)),
                ('tCorner', models.CharField(max_length=400)),
                ('ftCorner', models.CharField(max_length=400)),
                ('img', models.ImageField(upload_to='upload_images/')),
                ('gallery_images', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gsoc2019.Gallery')),
            ],
        ),
    ]
