# Generated by Django 2.2.1 on 2019-07-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gsoc2019', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='burntArea',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
